
inputFile:   ""
barcodeFile: "/home/ubuntu/barcoded_yeast/barcoding_summary.txt"
basecaller:  "Guppy 3.3.0"
flowcellId:  "FAKXXXX"
tutorialText: FALSE

# **inputFile** - this should be the sequencing_summary.txt from Guppy etc
# move your own sequence_summary.txt file (or concatenation thereof) to the
# RawData folder to run analysis on your own sequence collection

# **barcodeFile** - if Guppy_barcoder has been used to demultiplex library,
# move the barcoding_summary.txt file to the RawData folder and update variable

# **basecaller** and **flowcellId** - are used for presentation in report
# please update to correspond to your sequence analysis

# change the **tutorialText** value to FALSE to mask  tutorial instructions
